name: Release
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-verify:
    name: Build and Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron
      - name: Install dependencies
        run: npm install
      - name: Build NPM package
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-content
          path: out/

  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    needs: build-verify
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: static-content
          path: out/
      - name: Checkout target
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.DEPLOY_REPO }}
          path: 'deploy'
          token: ${{ secrets.DEPLOY_PAT }}
      - name: Deploy files to target
        run: |
          rm -r deploy/*
          cp -r out/. deploy/
          cd deploy
          touch .nojekyll
          echo ${{ vars.DEPLOY_URL }} > CNAME
          git add .
          git commit -m $GITHUB_SHA
          git push

  deploy-production:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-staging
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: static-content
          path: out/
      - name: Checkout target
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.DEPLOY_REPO }}
          path: 'deploy'
          token: ${{ secrets.DEPLOY_PAT }}
      - name: Deploy files to target
        run: |
          rm -r deploy/*
          cp -r out/. deploy/
          cd deploy
          touch .nojekyll
          echo ${{ vars.DEPLOY_URL }} > CNAME
          git add .
          git commit -m $GITHUB_SHA
          git push          
